### ISSUE TITLE
Could the generated file be placed somewhere else?

### ISSUE THREAD

**Issue by periloso** [martinlindhe/laravel-vue-i18n-generator#1]
Since I'm not using browserify, I'd like to put the generated file somewhere else (inside public in my case); is there a way to do it without forking the project and modifying the sources? AFAIK, the path is hardcoded into `laravel-vue-i18n-generator/src/Commands/GenerateInclude.php`.

**Comment by martinlindhe** [comment]
you could move the generated file in your asset build script. patch also welcome to override the hardcoded path

**Comment by periloso** [comment]
Okay, will take a look at it. :)

**Comment by martinlindhe** [comment]
ps, I'm also not using browserify :-)

**Comment by periloso** [comment]
Patch made. :)

**Comment by martinlindhe** [comment]
patch accepted, thanks for this!

**Comment by martinlindhe** [comment]
also released 0.1.6 with your patch, so it can be picked by composer

**Comment by periloso** [comment]
Well, my pleasure... this package is really useful! :)
