### ISSUE TITLE
Pluralization now can work ?

### ISSUE THREAD

**Issue by BRKsDeadPool** [martinlindhe/laravel-vue-i18n-generator#12]
First of all thank you, this is a very useful package, without it I would have a lot, a lot of work to do.

In the documentation it is written that the i18n plugin does not support pluralization, but from its current documentation, pluralization is part of the core code now.

How can i use this feature now ?

**Comment by martinlindhe** [comment]
It is not implemented, patch welcome :-)

**Comment by davidsoderberg** [comment]
I think this will work out of the box, just use the latest version of vue-i18n :)

**Comment by martinlindhe** [comment]
@davidsoderberg Cool, have you tried it out? I've not had time to look into it yet.
As far as I remember, the note in the readme just stated the fact that vue-i18n didn't at the time, support pluralization. If it is different than how Laravel does it, there is currently no code converting to the vue-i18n format.

**Comment by martinlindhe** [comment]
Pluralization works, just use "single form|multiple form" syntax
