### ISSUE TITLE
Is this package maintained?

### ISSUE THREAD

**Issue by pmkay** [martinlindhe/laravel-vue-i18n-generator#127]
Hello,

I'm planning on using your package for my project but i'm not sure if this package is being maintained currently or not. On your readme you say that the package is no longer maintained, but I see that this package has compatibility with Laravel 7.0+ and latest commit was done 14 days ago. It would be great if you can clarify if this package is maintained and is usable for foreseeable future, thanks!

**Comment by martinlindhe** [comment]
The readme is correct.
