### ISSUE TITLE
Empty i18n arrays in created vue-i18n-locales.generated.js file

### ISSUE THREAD

**Issue by simtrax** [martinlindhe/laravel-vue-i18n-generator#15]
The package does not fetch the translations as I expected it to.
Is the i18n arrays supposed to be empty like this? 
`    
"i18n": {
        "ro_RO": {
            "LC_MESSAGES": []
        },
        "sv_SE": {
            "LC_MESSAGES": []
        }
    }
`
I have two languages  where I have translations from sv_SE to ro_RO. All the other out of the box Laravel specific validation messages are working.

**Comment by martinlindhe** [comment]
Hello! How does your laravel translation file look? I am curious what LC_MESSAGES is doing here. It usually is the name of a system envoronment variable that controls the language of text in your Linux shell.

**Comment by simtrax** [comment]
I've used [laravel-gettext](https://github.com/xinax/laravel-gettext) to genereate translations for the site. Using blade to translate strings in my views based on the locale setting of the app. With the help of that package.
Now I'd like to translate strings in my vue components, hoping that this package could help me out. But I could've gotten everything wrong. I can imagine it's kind of tricky, cause I'd like Vue to get it's translations from the laravel-gettext package.
Am I on the right track? Otherwise I'll have to keep searching. I'll paste an image of my Laravel lang folder.
![skarmavbild 2017-05-06 kl 09 14 37](https://cloud.githubusercontent.com/assets/10018647/25770692/7baf576c-323c-11e7-8154-082ac630633f.png)

**Comment by martinlindhe** [comment]
Okay. This program reads the laravel translation json files, and is not compatible wirh .po and .mo files from laravel-gettext.

**Comment by martinlindhe** [comment]
s/json files/php arrays/
