### ISSUE TITLE
Laravel Spark Implementation

### ISSUE THREAD

**Issue by securit** [martinlindhe/laravel-vue-i18n-generator#17]
How would this work with Spark?

**Comment by martinlindhe** [comment]
I have no experience of laravel spark, so I don't know straight off.
But it seems that spark is built on top of laravel, (?), it should then allow use of normal laravel extensions like this one.

Please let me know if you give it a try

**Comment by martinlindhe** [comment]
Another user confirmed he is using Laravel Spark and posted his config here: https://github.com/martinlindhe/laravel-vue-i18n-generator/issues/33#issuecomment-343539660

So I am considering this "working" :-)
