### ISSUE TITLE
UMD style export instead of ES6 module

### ISSUE THREAD

**Issue by dobromir-hristov** [martinlindhe/laravel-vue-i18n-generator#18]
Could we get an UMD style export, so we can import the built file it into a build system or in the browser directly? 
I am asking because If I let a translator translate stuff in my backend, I have to go in and pull all the translations, run artisan command to generate the .js file, then run my build commands so I can build my app.js again. If it was an umd module, I could just import it in the browser and call it from an Event for example.
I can try and do a PR if that would help?

**Comment by martinlindhe** [comment]
Sounds good, PR welcome! Please implement it something like this:

* keep existing behaviour if command is invoked as documented.

* Add a --umd command line flag, to output in UMD style, so you can invoke:
```php artisan vue-i18n:generate --umd```
or similar

**Comment by dobromir-hristov** [comment]
I forgot to document the new feature in the readme.md
Would you like to do it, or shall I do another PR ?

**Comment by martinlindhe** [comment]
It would be helpful if you have time, please send a PR. If not, I'll get around to update README eventually

**Comment by martinlindhe** [comment]
Either way, thanks so much for your contribution :)
