### ISSUE TITLE
Component based localization 

### ISSUE THREAD

**Issue by ferleal** [martinlindhe/laravel-vue-i18n-generator#20]
I was testing the idea on having individual locales files like the ones we have on laravel side, so if you are using vue-router to create a SPA , can be used on the component  like this [https://kazupon.github.io/vue-i18n/en/component.html](https://kazupon.github.io/vue-i18n/en/component.html) and we can use webpack 2 advantage of code splitting and dynamic loading, instead of having a big locale file.

**Comment by martinlindhe** [comment]
Sounds interesting :-) Do you have an idea of how it should be implemented?

**Comment by ferleal** [comment]
I just implemented on my fork,  check it out, I coded it quickly so maybe it needs some refactoring  :p 
[https://github.com/ferleal/laravel-vue-i18n-generator/commit/b737bfae6188beb9e8be52acc345bed7e2a09b88](https://github.com/ferleal/laravel-vue-i18n-generator/commit/b737bfae6188beb9e8be52acc345bed7e2a09b88)

**Comment by martinlindhe** [comment]
Nice work! added a comment or two, please send a PR =)

**Comment by martinlindhe** [comment]
This was resolved in #22
