### ISSUE TITLE
error Vue.locale is not a function

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [martinlindhe/laravel-vue-i18n-generator#27]
Hello,
thank for this package (but its not working for me :) )
i get this message after make everything like description:

```
Uncaught TypeError: Vue.locale is not a function
    at app.js:18
    at Array.forEach (<anonymous>)
    at Object../resources/assets/js/app.js (app.js:17)
    at __webpack_require__ (bootstrap 1b252795b9032e827bb4:54)
    at Object.0 (app.js?id=549aa35d4febc37b4843:31457)
    at __webpack_require__ (bootstrap 1b252795b9032e827bb4:54)
    at webpackJsonpCallback (bootstrap 1b252795b9032e827bb4:25)
    at app.js?id=549aa35d4febc37b4843:1
```

and the package installed in fresh laravel 5.5 project.
versions:
"vue-i18n": "^7.1.1",
"vue": "^2.1.10"

**Comment by martinlindhe** [comment]
I guess vue-i18n changed their API again. You should have better success if you pin it to version 5 or something, I hope. Their changelog basically just says "Breaking changes - API" here for version 6.0, https://github.com/kazupon/vue-i18n/blob/dev/CHANGELOG.md#boom-breaking-changes-2


They have some version 6/7+ example here, maybe you can work it out
http://kazupon.github.io/vue-i18n/en/migrations.html#global-methods

**Comment by thmsbkkr** [comment]
Hi Martin,

I came across this same error when trying to set it up. I'm using Vue, Vue-Router and Vuex.
Been searching for the solution on the github issues page of vue-i18n but haven't had any luck.

For what it's worth, here is my file.

```
import axios from 'axios'

axios.defaults.headers.common['X-CSRF-TOKEN'] = window.App.csrfToken;
axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import VeeValidate from 'vee-validate'
import VueInternalization from 'vue-i18n'
import Locales from './vue-i18n-locales.generated.js';

Vue.use(VueInternalization)
Vue.use(VeeValidate, { inject: false })

Vue.config.lang = 'en';

Object.keys(Locales).forEach(function (lang) {
    Vue.locale(lang, Locales[lang])
});

import router from './router'
import store from './store'
import App from './App.vue'

Vue.config.productionTip = false

/* eslint-disable no-new */
const app = new Vue({
    el: '#app',
    router,
    store,
    template: '<App/>',
    components: { App }
})
```

Thank you! :)

**Comment by martinlindhe** [comment]
@thmsbkkr as a work around you can use version 5 of vue-i18n.

If you want to try with version 7 you could have a look at the example at http://kazupon.github.io/vue-i18n/en/migrations.html#global-methods

It looks like you just need to pass the array outputted by this plugin to the VueI18n constructor.

Something like
```
import Locales from './vue-i18n-locales.generated.js';
const i18n = new VueI18n(Locales);
const app = new Vue({ i18n }).$mount('#app');
```
should work I think


I'll have a look when I'm back to normal workage, am travelling

**Comment by Konafets** [comment]
@martinlindhe Did you looked into this or still hitting the road :-)

I got around the error by the following code:

```js
import VueInternalization from 'vue-i18n';
import Locales from './vue-i18n-locales.generated.js';

Vue.use(VueInternalization);
const i18n = new VueInternalization(Locales);

import store from './vuex';

const app = new Vue({
    store, // inject store into all children
    el: '#app',
    i18n
});
```

But now I got this error when using `$t` in my templates:
`Cannot translate the value of keypath 'message.hello'. Use the value of keypath as default.`

**Update**: I got it to work. See at #29.

**Comment by martinlindhe** [comment]
@Konafets Nice work
no this has slipped my mind.
Great you got it working with vuex-i18n,
but I think we should try get it to work with the recent vue-i18n too

**Comment by Konafets** [comment]
@martinlindhe I thought about to *fork* your lib by taking the generator part and make it compatible with vuex-i18n or would you be open to make your lib be compatible with both vuex-i18n and vue-i18n.

A big favor of vuex-i18n is, that it supports plural but that need some extra string replacement in the generator.

**Comment by martinlindhe** [comment]
@Konafets I would gladly extend this lib to also work with vuex-i18n. However, from your post at https://github.com/martinlindhe/laravel-vue-i18n-generator/issues/29#issue-264570535 I got the impression no fork was needed, only some different setup instructions, correct?

**Comment by Konafets** [comment]
One difference between the libs is the way to handle pluralization. While vue-i18n does it the _Laravel way_ using the pipe symbol `|`, vuex-i18n uses three collons `person ::: people`. I would introduce a flag in the config to be able to switch between both libs and replace the `|` by `:::` when using vuex-i18n.

**Comment by martinlindhe** [comment]
I see, sounds reasonable!

**Comment by martinlindhe** [comment]
Closing this as a dupe in favor for #40
