### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by andredewaard** [martinlindhe/laravel-vue-i18n-generator#3]
`
vue-i18n-locales.generated.js?7708:1 Uncaught SyntaxError: Unexpected token export(anonymous function) @ web.js:1351__webpack_require__ @ web.js:556fn @ web.js:87(anonymous function) @ web.js?f2b0:6(anonymous function) @ web.js:782__webpack_require__ @ web.js:556fn @ web.js:87(anonymous function) @ web.js:587__webpack_require__ @ web.js:556(anonymous function) @ web.js:579(anonymous function) @ web.js:582
client.js?c49f:58 [HMR] connected
`

I import it like this:
`
import Vue from 'vue'
import vueViewport from 'vue-viewport'
import vueResource from 'vue-resource'
import VueI18n from 'vue-i18n'

import Locales from './../../vue-i18n-locales.generated.js'

Vue.use(vueViewport)
Vue.use(vueResource)
Vue.use(VueI18n)

Vue.config.lang = 'nl'

Vue.use(VueI18n, {
  lang: 'nl',
  locales: Locales
})
`

And using babel to compile this.

**Comment by martinlindhe** [comment]
Hi, and thanks for reporting. Can you post your vue-i18n-locales.generated.js please?

**Comment by martinlindhe** [comment]
Ah, I think your issue might be that you need to use ES6 for the export keyword to work. You might need to upgrade babel to a more recent version (6.0 should be enough)

**Comment by martinlindhe** [comment]
The " Unexpected token export" is because your toolchain don't recognize the es6 module syntax used.
For this to work, you need to enable ES6 (aka es2015) in your .babelrc, like this:

```
{
  "presets": ["es2015"]
}
```

Please let me know whether this solves your issue, and don't hesitate to post more issues!

**Comment by martinlindhe** [comment]
I hope this helps, and sorry for the shattered comments. I had to read up on babel to make a guess on the issue. Please let me know wether this sorts it out, and don't hesitate to post more issues!

**Comment by martinlindhe** [comment]
closing this issue. please get in touch if you still have issues

**Comment by andredewaard** [comment]
Sorry. Got it to work differently.
Tried it your way now and still doesn't work. I use this template for use of webpack: 
https://github.com/dolbex/webpack-laravel

I have a file .babelrc that looks like this: 
{
  "presets": ["es2015", "stage-2"],
  "plugins": ["transform-runtime"],
  "comments": false
}

**Comment by martinlindhe** [comment]
Thanks @andre-dw !
Could you maybe share your working setup for later reference?

best regards
Martin

**Comment by andredewaard** [comment]
I replaced the generated file to a different location and it works now. Only thing is that eslint is whining about dubble qoutes. So trying to figure out if jshint will ignore that file.

**Comment by martinlindhe** [comment]
Thanks to #2, it should be possible to specify a custom output path in the config file. Maybe that will help you?

Second, it would be interesting to see what input is causing double quotes (could you paste the lines that has double quote warnings?)

If laravel-vue-i18n-generator is creating the double quotes we need to fix that!

**Comment by andredewaard** [comment]
Yes, that fixed the first problem for me. I moved the file to the directory where all the Javascript files are.

Second, The file being generated by vue-i18n-generator contains only double quotes on the key and the value. I fixed this to add a .eslintigore file and include the generated file in there. I can't see where the double quotes are being created in your generator.php
