### ISSUE TITLE
[FEATURE] Support for vee-validate and other validators

### ISSUE THREAD

**Issue by psychonetic** [martinlindhe/laravel-vue-i18n-generator#32]
Hello,

I am using vee-validate and it would be great if laravels validation file could be used for vee-validate messages.
It should be really easy to implement.
The only changes are the following:
- single file for each locale
- all {attribute} must be replaced with {field}
- an extra file for validation rules for vee-validate, because they have the following structure:
```
const messages = {
  _default: (field) => `The ${field} value is not valid.`,
  in: (field) => `The ${field} field must be a valid value.`,
  //etc..
};

const locale = {
  name: 'en',
  messages,
  attributes: {}
};

export default locale
```

This is really great for custom rules, so you don't need to define those rules on server and also client side.
Let me know what you guys think.

Cheers,

Marco

**Comment by martinlindhe** [comment]
Patches are welcome!
It would be great if you could help implement this functionality, since you are interested in having it :-)

**Comment by martinlindhe** [comment]
Hi again @psychonetic 
Thinking again on this one, I believe maybe such feature would be better implemented in another part of the stack. This project is strictly a tool to get your translation files in sync between your Laravel backend and your Vue frontend. In your Vue frontend, you should probably better call the vue-i18n translation function to use these translations automatically. Based on your example, maybe something like:

```js
const messages = {
  _default: (field) => $t("The ${field} value is not valid."),
  in: (field) => $t("The ${field} field must be a valid value."),
  //etc..
};
```

I'm gonna close this ticket, please add more info if you still feel this should be implemented here.
