### ISSUE TITLE
Reading translations from multiple locations

### ISSUE THREAD

**Issue by gsusanj** [martinlindhe/laravel-vue-i18n-generator#35]
I have a separated my application in separate modules (using nwidart/laravel-modules), now I have language files in different folders. Could you add support to add multiple folders to read the language files from?

**Comment by martinlindhe** [comment]
Does these nwidart/laravel-modules modues each have their own composer.json file?

If so, you should set up laravel-vue-i18n-generator for each module

**Comment by gsusanj** [comment]
Ehh sorry, I first said they don't, but they do. I will see how it works.

**Comment by martinlindhe** [comment]
Okay, then just use this package as intended, for each of these modules.

**Comment by uisumo** [comment]
Hi,

Iam using nwart module structure and install nwidart/laravel-modules in one of my module and configured as mentioned, but and trying to publish the config file with command in module (Which means I ran the following command in a module):

`php artisan vendor:publish --provider="MartinLindhe\VueInternationalizationGenerator\GeneratorProvider"`

`php artisan vue-i18n:generate`

But it is saying "Could not open input file: artisan" 

Can any help here.

Thanks,
- Adi

**Comment by martinlindhe** [comment]
> But it is saying "Could not open input file: artisan"
> 
> Can any help here.

artisan is part of Laravel, see https://laravel.com/docs/5.7/artisan
