### ISSUE TITLE
[Question] Contribution.

### ISSUE THREAD

**Issue by roseffendi** [martinlindhe/laravel-vue-i18n-generator#36]
I want to make some contribution but i have a problem when running tests.
I think it was because the DirectoryIterator didn't return the same directory structure as the OS filesystem. It randomly sorted.

expected - (result):
[0]. (sv)
[1].. (..)
[2]en (en)
[3]sv (.)

Do you have any solution for this problem ?

PS: My environtment is Laravel Homestead

**Comment by martinlindhe** [comment]
Maybe one could sort the list inside the test before checking for expected result

**Comment by martinlindhe** [comment]
@roseffendi I'll go ahead and close this, please reopen if we didn't fully resolve it in #37
