### ISSUE TITLE
ErrorException on Generator.php

### ISSUE THREAD

**Issue by janokary** [martinlindhe/laravel-vue-i18n-generator#4]
Hi I get this error when trying to run

php artisan vue-i18n:generate

`[ErrorException]                                                                                                                                           
  Argument 1 passed to MartinLindhe\VueInternationalizationGenerator\Generator::adjustArray() must be of the type array, integer given, called in /home/dev/laravel/vendor/martinlindhe/laravel-vue-i18n-generator/src/Generator.php on line 49 and defined`

**Comment by ferleal** [comment]
try running 
`php artisan vendor:publish`

**Comment by martinlindhe** [comment]
@janokary: did the comment from @ferleal solve your issue?
(if so, we need to update the README)

**Comment by martinlindhe** [comment]
@janokary: did above comments solve your issue? if so could you please close this ticket

**Comment by janokary** [comment]
Yes it did. Than you all.
