### ISSUE TITLE
Can't install on L5.4

### ISSUE THREAD

**Issue by voicecode-bv** [martinlindhe/laravel-vue-i18n-generator#44]
Hi Martin, 

First of all, thanks for this great package. I'm using it for a L5.6 project and want to use it for another L5.4 project as well. But it seems it wouldn't install correctly, because no vendor files are being published and when I run vue-i18n:generate, I'm getting an error saying "There are no commands defined in the "vue-i18n" namespace. 

I did add MartinLindhe\VueInternationalizationGenerator\GeneratorProvider::class, to the list of providers and when I run composer show, I actually see the package listed. 

Got any idea what to do next?

Thanks!
Michael

**Comment by martinlindhe** [comment]
Not sure what could be wrong.
This project has been around and working since Laravel 5.3 and no breaking changes have been made, so it should still work.

**Comment by voicecode-bv** [comment]
@martinlindhe I've noticed other packages wouldn't publish any config files as well. When I was searching for that issue, I saw the following solution which had to do something with config cache. 

1- Add service provider to providers array on the config/app.php
2- Run php artisan config:cache
3- Run composer update
4- Run php artisan config:cache
5- Run php artisan vendor:publish
