### ISSUE TITLE
How can I import only one translation file?

### ISSUE THREAD

**Issue by AlsonicTech** [martinlindhe/laravel-vue-i18n-generator#45]
In ```config/vue-i18n-generator.php``` we have this line ```'langPath' => '/resources/lang',``` from where we can set the trans files path. 

But if I want to add only one translation file to my vue app?
Right now I have many translation files, but I need only one for the vue app, and I dont want to export all of the files in the json. How can I do this?

**Comment by martinlindhe** [comment]
laravel-vue-i18n-generator simply keeps your laravel translations in sync with your vue app. That means all translations is kept in sync. This generally works well as your frontend grows, so you won't need to keep exporting another bunch of translation strings as you keep working.

If you are interested in this feature, perhaps you can help me add some command line switch to specify a file whitelist for inclusion.

**Comment by AlsonicTech** [comment]
@martinlindhe Yes, the idea is that the project has just a small part made in vue (spa), and it has dozens of trans files, but I need just one file for the vue app. I will look over the code, maybe we can add a whitelist.

**Comment by martinlindhe** [comment]
@Al3xR0 I see.

Another way of resolving it without additional code is if you split your php project into multiple projects where just one share translations with the vue frontend.

**Comment by AlsonicTech** [comment]
@martinlindhe #46

**Comment by martinlindhe** [comment]
@Al3xR0 I have now released version 0.1.27 with your changes included.

Could you give it a spin and let me know if everything works good on your end?

**Comment by AlsonicTech** [comment]
@martinlindhe I actually receive an error where trying to install the new version on a laravel 5.3

```
> php artisan optimize
[Symfony\Component\Debug\Exception\FatalThrowableError] 
Type error: Argument 1 passed to Illuminate\Console\Application::add() must be an instance of Symfony\Component\Console\Command\Command, instance of MartinLindhe\VueInternationalizationGenerator\Generator given, called in /PROJECT/vendor/laravel/framework/src/Illuminate/Console/Application.php on line 158 
```

**Comment by martinlindhe** [comment]
I'm really sorry about this.

I screwed up a bit when trying to do some house keeping of the code last night.
I have tried to revert the remaining offending parts. Would you please let me know if it works this time around? Version 0.1.28

**Comment by AlsonicTech** [comment]
@martinlindhe works perfect now. Thanks!

**Comment by martinlindhe** [comment]
@Al3xR0 great, thanks for testing!
