### ISSUE TITLE
How can I use $t in vue.js methods?

### ISSUE THREAD

**Issue by rafailml** [martinlindhe/laravel-vue-i18n-generator#51]
I'm trying to use $t() In vue.js methods, because of pluralization.
Something like that:
```
pluralCheck() {
                if(1){
                    return $t('messages.one');
                }else{
                    return $t('messages.many')
                }
            }
```
But I'm getting: ReferenceError: $t is not defined
How can I use this in methods or how to deal with pluralization?

Thanks!

**Comment by martinlindhe** [comment]
$t() is defined in vue-i18n, see https://kazupon.github.io/vue-i18n/en/started.html
or vuex-i18n, see https://github.com/dkfbasel/vuex-i18n#usage

Please refer to their documentations and issue trackers, as the $t is not a functionality of this project.

**Comment by YoshiMannaert** [comment]
For anyone coming across this problem: 
The way to use the translations in methods is by using `this.$t('messages.one')`

**Comment by martinlindhe** [comment]
> 
> 
> For anyone coming across this problem:
> The way to use the translations in methods is by using `this.$t('messages.one')`

This is incorrect, both vue-i18n and vuex-i18n offers a $t() method if set up correctly. Refer to their respective documentation.

**Comment by YoshiMannaert** [comment]
> > For anyone coming across this problem:
> > The way to use the translations in methods is by using `this.$t('messages.one')`
> 
> This is incorrect, both vue-i18n and vuex-i18n offers a $t() method if set up correctly. Refer to their respective documentation.

While I haven't found anything in the documentation immediately, I have come across several issues where `this.$t()` is used for accessing the translation **outside of the Vue template**. 

So this does seem to be the way to use it, as you can see [here](https://github.com/kazupon/vue-i18n/issues/149#issuecomment-296348086), or [here](https://github.com/kazupon/vue-i18n/issues/149#issuecomment-300096155) as mentioned by the owner of vue-i18n repository (`this.i18n.t` can be replaced with `this.$t`).

All I'm trying to say is that this works for me and if someone comes across this problem they can see if it would work for them.
