### ISSUE TITLE
translation script in vue 

### ISSUE THREAD

**Issue by fazreenarahman** [martinlindhe/laravel-vue-i18n-generator#52]
I am using your generator. I have this code: 

```
if(!self.form.deliveryService)
                {
                    self.formError.deliveryService = 'Loading services...';
                    swal('Loading services...');
                    swal.showLoading();
                }else {
                    self.formError.deliveryService = 'Loading the service...';
                }
```

How do i translate the 'loading services'? Tried {{$t(vue.loadingservices')}} but nothing appears.

**Comment by martinlindhe** [comment]
For usage instructions of vue-i18n or vuex-i18n, please see their respective documentations.

http://kazupon.github.io/vue-i18n/

or

https://github.com/dkfbasel/vuex-i18n#usage

Hope this helps!
