### ISSUE TITLE
Support Laravel 5.7 (dev)

### ISSUE THREAD

**Issue by njoguamos** [martinlindhe/laravel-vue-i18n-generator#55]
On attempting to install on laravel 5.7, I get this error

- Installation request for martinlindhe/laravel-vue-i18n-generator ^0.1.28 -> satisfiable by martinlindhe/laravel-vue-i18n-generator[0.1.28].
- Conclusion: remove laravel/framework 5.7.x-dev
- Conclusion: don't install laravel/framework 5.7.x-dev

**Comment by martinlindhe** [comment]
Patch is welcome, if you are able to verify it working.

May just need to update the require block
https://github.com/martinlindhe/laravel-vue-i18n-generator/blob/master/composer.json#L13
