### ISSUE TITLE
Generate separate files for separate locales?

### ISSUE THREAD

**Issue by ngstwr** [martinlindhe/laravel-vue-i18n-generator#56]
Is it possible to generate separate vue-i18n-locales files for separate locales?

I don’t want to load all the locales in the initial load, want to lazy load the locales using Vuex-i18n.

**Comment by martinlindhe** [comment]
Yes, the command can be invoked with the `--multi` parameter was implemented in #22, however it is not mentioned in the README.

**Comment by ngstwr** [comment]
Thanks! 

I apologise for replying late, I missed the notification of your reply.

I wanted to generate separate locale files based on language. --multi parameter generates separate locale files for separate modules.

**Comment by martinlindhe** [comment]
Okay, in that case a patch is welcome for your use-case.

**Comment by martinlindhe** [comment]
@ngstwr Should be implemented with #82 so I'm closing this
