### ISSUE TITLE
Error on creating file

### ISSUE THREAD

**Issue by voicecode-bv** [martinlindhe/laravel-vue-i18n-generator#59]
Hello, 

When I run php artisan vue-i18n:generate I get the following error:

```
/vendor/martinlindhe/laravel-vue-i18n-generator/src/Commands/GenerateInclude.php : 48

  2   MartinLindhe\VueInternationalizationGenerator\Commands\GenerateInclude::handle()
      /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 29
```
On top of this, the complete json is beeing printed so I can't see what's happening exactly. 
I'm using the latest version of this package with Laravel 5.7.3

Is there some way I can see what's going on?

Thanks!

**Comment by voicecode-bv** [comment]
Just found the problem. The resources folder structure was updated in Laravel 5.7. Sorry :-)

**Comment by martinlindhe** [comment]
Thank you for reporting this!
For now I have updated the README with a notice in https://github.com/martinlindhe/laravel-vue-i18n-generator/commit/012424e1e167567b59a39b6e767e36128c4a123e
