### ISSUE TITLE
[vue-i18n] Cannot translate the value of keypath...

### ISSUE THREAD

**Issue by mehrancodes** [martinlindhe/laravel-vue-i18n-generator#6]
Installed the package on Laravel 5.3
Installed vue-i18n
generated the include file

then added:

``` javascript
window.Vue = require('vue');
import VueInternationalization from 'vue-i18n';
import Locales from './vue-i18n-locales.generated.js';

Vue.use(VueInternationalization, {
    lang: 'fa',
    locales: Locales
});
```

Now when adding a translate like {{ $t('app.email') }}, the browser-console give me this error message:

`[vue-i18n] Cannot translate the value of keypath "app.register_email". Use the value of keypath as default`

But when using this code, it works!

``` javascript
var VueI18n = require('vue-i18n')
import locales from './vue-i18n-locales.generated.js';

// set lang
Vue.config.lang = 'fa'

// set locales
Object.keys(locales).forEach(function (lang) {
  Vue.locale(lang, locales[lang])
})
```

**Comment by martinlindhe** [comment]
Are you using vue 2.0 or 1.0? Also what version of vue-i18n?
The example code were written for vue 1.0, I've not had time to check out vue 2.0 yet, if any changes are needed

**Comment by mehrancodes** [comment]
I'm using Vue 1.0 and vue-i18n is 4.4.1.
I found the example above from [this getting started example](https://kazupon.github.io/vue-i18n/started.html)

**Comment by martinlindhe** [comment]
Have you had success with the getting started steps from this project
https://github.com/martinlindhe/laravel-vue-i18n-generator#usage ?

The main difference I notice is the first line, should be
`import Vue from 'vue';`
In your second example, you are not importing vue at all.

Also, in both of your examples you are mixing require(), with import. I'm not sure that is working as expected.

**Comment by mehrancodes** [comment]
Thanks for your attention. sorry I just forgot to include Vue in the example above.
Already this is my code and it works:

``` javascript
window.Vue = require('vue');
var VueI18n = require('vue-i18n')
import locales from './vue-i18n-locales.generated.js';
Vue.config.lang = 'fa';
Object.keys(locales).forEach(function (lang) {
  Vue.locale(lang, locales[lang])
})
```

but when I switch to your ReadMe example, it doesn't work:

``` javascript
window.Vue = require('vue');
import VueInternationalization from 'vue-i18n';

import Locales from './vue-i18n-locales.generated.js';

Vue.use(VueInternationalization, {
    lang: 'en',
    locales: Locales
});
```

Also I can't find this export `VueInternationalization` from `vue-i18n`

**Comment by martinlindhe** [comment]
> but when I switch to your ReadMe example, it doesn't work

This is incorrect, your code is not the same as in the readme.
There is a fundamental difference in require() and import.
You should use the ES6 compatible "import", and not use require().

> Also I can't find this export VueInternationalization from vue-i18n

I think you are not fully aware how `import` works. In this case, the `VueInternationalization` is the name you use in your project to refer to the default imported module.  Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by martinlindhe** [comment]
closing this issue. please get in touch if you still are having issues

**Comment by gerardreches** [comment]
Hi, I'm trying to use this package on Laravel 5.3 with Vue 2.0 and I get the same error, and I'm not sure if it's because Vue 2.0 is not supported or if I'm doing something wrong. 

I have the `vue-i18n-locales.generated.js` under `resources/assets/js`, at the same level of the `app.js` file, where I coded this:

``` js
import VueInternalization from 'vue-i18n';
import Locales from './vue-i18n-locales.generated.js';

Vue.use(VueInternalization, {
    lang: 'es',
    locales: Locales
});
```

Before registering my Vue components, which are using the translations, but I get this error for each translation attempt:

`[vue-i18n] Cannot translate the value of keypath "home.welcome". Use the value of keypath as default`

@martinlindhe Any idea about which can be the problem? I implemented this incorrectly or is a package problem?

**Comment by martinlindhe** [comment]
@gerardreches I've not had time to test it with vue 2.0 yet, so I cannot answer if it is supposed to work.

There is an issue in vue-i18n that seems to be about the same issue, https://github.com/kazupon/vue-i18n/issues/49, where users seem to suggest it only happens on Windows. Are you running Windows by chance?

Also note that vue-i18n 4.1.0 claims support for vue 2.0 beta (which may or may not mean it works with  vue 2.0 final)

**Comment by gerardreches** [comment]
@martinlindhe Ok, now I can say that this package works with Vue 2.0 and Laravel 5.3, but the syntax to implement it has changed a little in order to work:

``` js
import VueInternalization from 'vue-i18n';
import Locales from './vue-i18n-locales.generated.js';

// install plugin
Vue.use(VueInternalization);

// set lang
Vue.config.lang = 'es';

// set locales
Object.keys(Locales).forEach(function (lang) {
  Vue.locale(lang, Locales[lang])
});
```

So, changing this in the README file you can say that the package works with Vue 2.0  😄

**Comment by martinlindhe** [comment]
@gerardreches Great find! I'll update the README. thanks for your help

**Comment by gerardreches** [comment]
And yeah, is exactly the piece of code that @mehranrasulian said at first. It's explained at [vue-i18n documentation](https://kazupon.github.io/vue-i18n/started.html).

**Comment by martinlindhe** [comment]
@gerardreches  Oh, guess we dont need a vue 1 / vue 2 section in the readme then, if same code works on both versions?

**Comment by gerardreches** [comment]
@martinlindhe I think that it depends on current _vue-i18n_ version, not in current vue version. So yes, the same code seems to work in both versions.

**Comment by martinlindhe** [comment]
@gerardreches okay thanks for clarifying!
