### ISSUE TITLE
Written to messages optional

### ISSUE THREAD

**Issue by voicecode-bv** [martinlindhe/laravel-vue-i18n-generator#61]
Hi Martin, 

Would it be possible to make the output messages optional? When using Artisan::call('vue-i18n:generate') in Laravel Nova this could break some JSON output as it's not valid JSON.

Update: just added a PR

**Comment by martinlindhe** [comment]
Sure, thanks for PR

**Comment by martinlindhe** [comment]
Released 0.1.30 with your PR included, thanks!
