### ISSUE TITLE
Not working for parameters in json files

### ISSUE THREAD

**Issue by SamuelNitsche** [martinlindhe/laravel-vue-i18n-generator#64]
Laravel supports translation strings. These files can look like this:
```
{
    "Hello :name": "Hello :name"
}
```

The package should generate following code in the `*.generated.js` file
```
{
    "Hello {name}": "Hello {name}"
}
```

What it actually generates is the following
```
{
    "Hello :name": "Hello {name}"
}
```

Therefore I cannot translate the string with this method `{{ $t("Hello {name}", { name: "John' }) }}`

**Comment by martinlindhe** [comment]
Could you give version 0.1.31 a try, it contains a fix for your issue
