### ISSUE TITLE
ReferenceError: Laravel is not defined

### ISSUE THREAD

**Issue by VConsulting** [martinlindhe/laravel-vue-i18n-generator#65]
Hello,

The explanation on UMD module is not very clear to me.
I did not quite understand the utility?

I also have the following error:
(View.config.lang = Laravel.language)
> ReferenceError: Laravel is not defined

Thank you

**Comment by martinlindhe** [comment]
The --umd option wraps the output as a Universal Module Definition.

> ReferenceError: Laravel is not defined

See the readme for usage examples.

**Comment by zhengfen** [comment]
I am too late to join the discussion, but maybe this answer can help someone. 
the example of --umd  is outdated, here is the code works for me: 
  with      "vue-i18n": "^8.12.0",

import VueInternationalization from 'vue-i18n';
Vue.use(VueInternationalization);
// import Locale from './vue-i18n-locales.generated.js';
const lang = document.documentElement.lang.substr(0, 2);
const i18n = new VueInternationalization({
    locale: lang,
    messages: window.vuei18nLocales,
    silentTranslationWarn: process.env.NODE_ENV === 'production'
});
