### ISSUE TITLE
Unnecessary escape character

### ISSUE THREAD

**Issue by GonzaloGPF** [martinlindhe/laravel-vue-i18n-generator#67]
Hello! 
First of all, thanks for this awesome package, it really helps!
But now I'm facing an issue, when I place html string in my translation's files, then, the generated .js shows unnecesary escape characters.

For example, in lang/en/test.php
`'test' => 'It is a <strong>Test</strong> ok!',`

Then, after generating, in my messages.js, It shows
`'test' => 'It is a <strong>Test<\/strong> ok!',`

Notice the unnecessary escape character. How could I fix this? If possible!

Thanks!

**Comment by martinlindhe** [comment]
Should be easy enough to write a isolated test case for this. I'll have a look soon.

However, for me this has never come up as i separate design from text. It's a good idea to keep them separated :-)

**Comment by martinlindhe** [comment]
I had a look at this.
The current behaviour is correct as far as I can tell. Your output should have double qoutes and should look like this:

```
"test" => "It is a <strong>Test<\/strong> ok!",
```

Not like the single quoutes in your bug report. Thus / needs to be escaped to be treated correctly.

You can read more about this at https://www.w3schools.com/js/js_strings.asp under the heading Special Characters.

I'm going to close this, but feel free to add additional comments if you think this is incorrect.

**Comment by martinlindhe** [comment]
Had a closer look at this issue today.

Turns out this is the standard behaviour of php's json_encode().

There are some explanations of this here https://stackoverflow.com/a/10314758

**Comment by martinlindhe** [comment]
I found a solution, and released 0.1.32 with a fix to not escape slashes.
