### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by voicecode-bv** [martinlindhe/laravel-vue-i18n-generator#75]
Hi Martin, 

Will this package be ready for Laravel 5.8 soon?

Thanks!

Michael

**Comment by martinlindhe** [comment]
I have no ETA. Please let me know if you are interested in working on this.

**Comment by martinlindhe** [comment]
So far the 5.x series upgrades has mostly been adjusting these lines:

https://github.com/martinlindhe/laravel-vue-i18n-generator/blob/master/composer.json#L15-L16

**Comment by voicecode-bv** [comment]
Sure! Will take a look at it in a bit. Thanks!

**Comment by voicecode-bv** [comment]
Just submitted a PR, will close this now.
