### ISSUE TITLE
Subdirectories in the language folder cause errors

### ISSUE THREAD

**Issue by tomcoonen** [martinlindhe/laravel-vue-i18n-generator#8]
When putting language files in subdirectories, these directories cause an error:
Undefined index: extension

Would be nice to scan subdirectories.

**Comment by martinlindhe** [comment]
@tomcoonen This should be resolved by #9, could you give it a try?

**Comment by martinlindhe** [comment]
Support for this feature was released in 0.1.8. If you still are having issues, please open a new issue.
