### ISSUE TITLE
Exclude a directory ?

### ISSUE THREAD

**Issue by ghost** [martinlindhe/laravel-vue-i18n-generator#81]
Is there a way to exclude a directory?

I have a front-end lang folder which have files
- index.php
- other files

And an back-end lang folder which have files

- index.php
- other files

And that wont work with the config exclude, since both files have the same names..

**Comment by martinlindhe** [comment]
Yes,

You can define a root directory as 'langPath' in https://github.com/martinlindhe/laravel-vue-i18n-generator/blob/master/src/config/vue-i18n-generator.php#L14

**Comment by ghost** [comment]
Never mind, thank you!
