### ISSUE TITLE
pluralization

### ISSUE THREAD

**Issue by gretter** [martinlindhe/laravel-vue-i18n-generator#89]
Hello,
in the github page of [vuex.i18n](https://github.com/dkfbasel/vuex-i18n) is written they support pluralization. Can you add support of this functionality?

See the description bellow:

> Basic pluralization is also supported. Please note, that the singular translation must be specified first, followed by plural translations denoted by `:::`. Up to six pluralization forms are supported based on configuration taken from vue-gettext. The second option is used for variable replacements. The third option to define if the singular or pluralized translation should be used (see below for examples).

**Comment by martinlindhe** [comment]
You need to use "single form|multiple form" syntax. See #12
