### ISSUE TITLE
Multiple-locales does not include json files

### ISSUE THREAD

**Issue by murrant** [martinlindhe/laravel-vue-i18n-generator#92]
My application has both json and php language files.  Both are included when I do a single file, but if I add --multiple-locales, json is not included in the output.

**Comment by martinlindhe** [comment]
Not a bug. This software is used to translate the Laravel translations (PHP files) into JSON for consumption by a js frontend such as vue-i18n

**Comment by murrant** [comment]
@martinlindhe I am talking about official Laravel translations.

https://laravel.com/docs/localization#using-translation-strings-as-keys

**Comment by martinlindhe** [comment]
@murrant you are welcome to provide a patch to resolve your issue

**Comment by murrant** [comment]
I have one that fixes my use case but I wasn't sure what was expected for the multiple files option (which my patch breaks).  Tests for these would help.

**Comment by murrant** [comment]
Fixed by #96
